services:
  producer:
    build:
      context: .
      args:
        KAFKA_BROKER: "kafka:29092"
        SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      dockerfile: producer.Dockerfile
    networks:
      - stateful-stream-processing-network

  consumer:
    build:
      context: .
      args:
        KAFKA_BROKER: "kafka:29092"
        SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
        CONSUMER_GROUP: "Consumer1"
        DB_HOST: "db"
        DB_PORT: "5432"
        DB_USERNAME: "postgres"
        DB_PASSWORD: "postgres"
        DB_NAME: twitter
      dockerfile: consumer.Dockerfile
    networks:
      - stateful-stream-processing-network
    depends_on:
      - producer

  processor:
    build:
      context: .
      args:
        DB_HOST: "db"
        DB_PORT: "5432"
        DB_USERNAME: "postgres"
        DB_PASSWORD: "postgres"
        DB_NAME: "twitter"
        WS_HOST: "0.0.0.0"
        WS_PORT: "8765"
        WS_WRITE_POOL_SIZE: "10"
      dockerfile: processor.Dockerfile
    networks:
      - stateful-stream-processing-network
    ports:
      - "8765:8765"
    depends_on:
      - consumer

networks:
  stateful-stream-processing-network:
    name: stateful_stream_processing_network
    external: true
